server:
  port: 8096

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microServices
    username: root
    password: ahmad#321
    # driver-class-name: com.mysql.cj.jdbc.Driver # Not needed if using the correct URL

  # JPA configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    xml:
      enabled: true
